// aimpactEditorPlugin.js
// This file is auto-generated by aimpact. It is automatically injected into the development build to
// enable communication with the Aimpact editor via aimpactEditorScript.js.
// This file will be automatically excluded from the production build.
// DO NOT MODIFY THIS FILE. ANY CHANGES WILL BE OVERWRITTEN.
import fs from 'fs';
import path from 'path';

export function aimpactEditorPlugin(options = {}) {
  const scriptPath = options.scriptPath || path.resolve(process.cwd(), 'aimpactEditorScript.js');
  return {
    name: 'inject-editor-events-script',
    transformIndexHtml(html) {
      const script = fs.readFileSync(scriptPath, 'utf-8');
      return html.replace(
        '</head>',
        `<script>${script}</script></head>`
      );
    },
    configureServer(server) {
      // Middleware to log runtime errors sent from the client
      server.middlewares.use('/__runtime_error__', (req, res) => {
        let data = '';
        req.on('data', chunk => (data += chunk));
        req.on('end', () => {
          console.error('[Runtime Error]', data);
          res.statusCode = 200;
          res.end('ok');
        });
      });
    },
  };
}
